version: '3.8'

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      CLUSTER_NAME: mascotas
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
    networks:
      - mascotas-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      SERVICE_PRECONDITION: "namenode:9000"
    networks:
      - mascotas-net

  spark-master:
    image: apache/spark:3.5.1
    user: root
    hostname: spark-master
    command: >
      bash -c "
      pip install numpy &&
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      "
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    networks:
      - mascotas-net
    volumes:
      - resultados_data:/tmp/resultados
      - predicciones_data:/tmp/predicciones
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  spark-worker:
    image: apache/spark:3.5.1
    hostname: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 
    networks:
      - mascotas-net
    deploy:
      replicas: 1

  dashboard:
    image: modulo_analitica-dashboard:latest
    ports:
      - "8501:8501"
    networks:
      - mascotas-net
    volumes:
      - resultados_data:/tmp/resultados
      - predicciones_data:/tmp/predicciones

  haproxy:
    image: modulo_analitica-haproxy:latest
    ports:
      - "80:80"
    networks:
      - mascotas-net

networks:
  mascotas-net:
    external: true

# =========================================================
# DEFINICIÓN CORRECTA DE VOLÚMENES PARA SWARM
# =========================================================
volumes:
  resultados_data:
    driver: local
  predicciones_data:
    driver: local