FROM apache/spark:3.5.1

USER root

RUN apt-get update && \
    apt-get install -y \
    python3 \
    openjdk-17-jre-headless && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

CMD ["python3", "simulador_mascotas.py"]